# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  jackalope.io:
    site_hosts:
      - jack3.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:masoninthesis/jackalope.io-jack3-.git
    site_install: true
    site_title: Example Site
    admin_user: admin
    admin_password: admin
    admin_email: admin@example.dev
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    system_cron: true
    env:
      wp_home: http://jack3.dev
      wp_siteurl: http://jack3.dev/wp
      wp_env: development
      db_name: jack3_dev
      db_user: jack3_dbuser
      db_password: jack3_dbpassword
